### ISSUE TITLE
Cannot play game after finishing first game

### ISSUE THREAD

**Issue by MarchandMD** [MarchandMD/battleship#38]
After a game is over, attempting to play a second game results in a commandline error and exiting out of the prorgram. 

```
        10: from runner.rb:3:in `<main>'
         9: from /Users/michaelmarchand/turing/1_mod/group_projects/battleship/lib/game.rb:50:in `start'
         8: from /Users/michaelmarchand/turing/1_mod/group_projects/battleship/lib/game.rb:147:in `game_loop'
         7: from /Users/michaelmarchand/turing/1_mod/group_projects/battleship/lib/game.rb:147:in `loop'
         6: from /Users/michaelmarchand/turing/1_mod/group_projects/battleship/lib/game.rb:149:in `block in game_loop'
         5: from /Users/michaelmarchand/turing/1_mod/group_projects/battleship/lib/game.rb:173:in `game_over'
         4: from /Users/michaelmarchand/turing/1_mod/group_projects/battleship/lib/game.rb:275:in `restart'
         3: from /Users/michaelmarchand/turing/1_mod/group_projects/battleship/lib/game.rb:84:in `place_computer_ships'
         2: from /Users/michaelmarchand/turing/1_mod/group_projects/battleship/lib/game.rb:99:in `place_computer_submarine'
         1: from /Users/michaelmarchand/turing/1_mod/group_projects/battleship/lib/game.rb:104:in `no_overlap'
/Users/michaelmarchand/turing/1_mod/group_projects/battleship/lib/game.rb:104:in `+': no implicit conversion of nil into Array (TypeError)
```

**Comment by MarchandMD** [comment]
this was solved by adding new boards to the player and computer, prior to restarting: 

```ruby
def restart
    @computer_board = Board.new
    @player_board = Board.new
    welcome_message
    place_computer_ships
    place_player_ships
    game_loop
  end
```
